export const adivinanzas = (level) => {
    switch (level) {
        case 1:
            return require('../../assets/img/acertijos/adivinanzas1.jpg');
        case 2:
            return require('../../assets/img/acertijos/adivinanzas2.jpg');
        case 3:
            return require('../../assets/img/acertijos/adivinanzas3.jpg');
        case 4:
            return require('../../assets/img/acertijos/adivinanzas4.jpg');
        case 5:
            return require('../../assets/img/acertijos/adivinanzas5.jpg');
        case 6:
            return require('../../assets/img/acertijos/adivinanzas6.jpg');
        case 7:
            return require('../../assets/img/acertijos/adivinanzas7.jpg');
        case 8:
            return require('../../assets/img/acertijos/adivinanzas8.jpg');
        case 9:
            return require('../../assets/img/acertijos/adivinanzas9.jpg');
        case 10:
            return require('../../assets/img/acertijos/adivinanzas10.jpg');
        case 11:
            return require('../../assets/img/acertijos/adivinanzas11.jpg');
        case 12:
            return require('../../assets/img/acertijos/adivinanzas12.jpg');
        case 13:
            return require('../../assets/img/acertijos/adivinanzas13.jpg');
        case 14:
            return require('../../assets/img/acertijos/adivinanzas14.jpg');
        case 15:
            return require('../../assets/img/acertijos/adivinanzas15.jpg');
        case 16:
            return require('../../assets/img/acertijos/adivinanzas16.jpg');
        case 17:
            return require('../../assets/img/acertijos/adivinanzas17.jpg');
        case 18:
            return require('../../assets/img/acertijos/adivinanzas18.jpg');
        case 19:
            return require('../../assets/img/acertijos/adivinanzas19.jpg');
        case 20:
            return require('../../assets/img/acertijos/adivinanzas20.jpg');
        case 21:
            return require('../../assets/img/acertijos/adivinanzas21.jpg');
        case 22:
            return require('../../assets/img/acertijos/adivinanzas22.jpg');
        case 23:
            return require('../../assets/img/acertijos/adivinanzas23.jpg');
        case 24:
            return require('../../assets/img/acertijos/adivinanzas24.jpg');
        case 25:
            return require('../../assets/img/acertijos/adivinanzas25.jpg');
        case 26:
            return require('../../assets/img/acertijos/adivinanzas26.jpg');
        case 27:
            return require('../../assets/img/acertijos/adivinanzas27.jpg');
        case 28:
            return require('../../assets/img/acertijos/adivinanzas28.jpg');
        case 29:
            return require('../../assets/img/acertijos/adivinanzas29.jpg');
        case 30:
            return require('../../assets/img/acertijos/adivinanzas30.jpg');
        case 31:
            return require('../../assets/img/acertijos/adivinanzas31.jpg');
        case 32:
            return require('../../assets/img/acertijos/adivinanzas32.jpg');
        case 33:
            return require('../../assets/img/acertijos/adivinanzas33.jpg');
        case 34:
            return require('../../assets/img/acertijos/adivinanzas34.jpg');
        case 35:
            return require('../../assets/img/acertijos/adivinanzas35.jpg');
        case 36:
            return require('../../assets/img/acertijos/adivinanzas36.jpg');
        case 37:
            return require('../../assets/img/acertijos/adivinanzas37.jpg');
        case 38:
            return require('../../assets/img/acertijos/adivinanzas38.jpg');
        case 39:
            return require('../../assets/img/acertijos/adivinanzas39.jpg');
        case 40:
            return require('../../assets/img/acertijos/adivinanzas40.jpg');
        case 41:
            return require('../../assets/img/acertijos/adivinanzas41.jpg');
        case 42:
            return require('../../assets/img/acertijos/adivinanzas42.jpg');
        case 43:
            return require('../../assets/img/acertijos/adivinanzas43.jpg');
        case 44:
            return require('../../assets/img/acertijos/adivinanzas44.jpg');
        case 45:
            return require('../../assets/img/acertijos/adivinanzas45.jpg');
        case 46:
            return require('../../assets/img/acertijos/adivinanzas46.jpg');
        case 47:
            return require('../../assets/img/acertijos/adivinanzas47.jpg');
        case 48:
            return require('../../assets/img/acertijos/adivinanzas48.jpg');
        case 49:
            return require('../../assets/img/acertijos/adivinanzas49.jpg');
        case 50:
            return require('../../assets/img/acertijos/adivinanzas50.jpg');
        case 51:
            return require('../../assets/img/acertijos/adivinanzas51.jpg');
        case 52:
            return require('../../assets/img/acertijos/adivinanzas52.jpg');
        case 53:
            return require('../../assets/img/acertijos/adivinanzas53.jpg');
        case 54:
            return require('../../assets/img/acertijos/adivinanzas54.jpg');
        case 55:
            return require('../../assets/img/acertijos/adivinanzas55.jpg');
        case 56:
            return require('../../assets/img/acertijos/adivinanzas56.jpg');
        case 57:
            return require('../../assets/img/acertijos/adivinanzas57.jpg');
        case 58:
            return require('../../assets/img/acertijos/adivinanzas58.jpg');
        case 59:
            return require('../../assets/img/acertijos/adivinanzas59.jpg');
        case 60:
            return require('../../assets/img/acertijos/adivinanzas60.jpg');
        case 61:
            return require('../../assets/img/acertijos/adivinanzas61.jpg');
        case 62:
            return require('../../assets/img/acertijos/adivinanzas62.jpg');
        case 63:
            return require('../../assets/img/acertijos/adivinanzas63.jpg');
        case 64:
            return require('../../assets/img/acertijos/adivinanzas64.jpg');
        case 65:
            return require('../../assets/img/acertijos/adivinanzas65.jpg');
        case 66:
            return require('../../assets/img/acertijos/adivinanzas66.jpg');
        case 67:
            return require('../../assets/img/acertijos/adivinanzas67.jpg');
        case 68:
            return require('../../assets/img/acertijos/adivinanzas68.jpg');
        case 69:
            return require('../../assets/img/acertijos/adivinanzas69.jpg');
        case 70:
            return require('../../assets/img/acertijos/adivinanzas70.jpg');
        case 71:
            return require('../../assets/img/acertijos/adivinanzas71.jpg');
        case 72:
            return require('../../assets/img/acertijos/adivinanzas72.jpg');
        case 73:
            return require('../../assets/img/acertijos/adivinanzas73.jpg');
        case 74:
            return require('../../assets/img/acertijos/adivinanzas74.jpg');
        case 75:
            return require('../../assets/img/acertijos/adivinanzas75.jpg');
        case 76:
            return require('../../assets/img/acertijos/adivinanzas76.jpg');
        case 77:
            return require('../../assets/img/acertijos/adivinanzas77.jpg');
        case 78:
            return require('../../assets/img/acertijos/adivinanzas78.jpg');
        case 79:
            return require('../../assets/img/acertijos/adivinanzas79.jpg');
        case 80:
            return require('../../assets/img/acertijos/adivinanzas80.jpg');
        case 81:
            return require('../../assets/img/acertijos/adivinanzas81.jpg');
        case 82:
            return require('../../assets/img/acertijos/adivinanzas82.jpg');
        case 83:
            return require('../../assets/img/acertijos/adivinanzas83.jpg');
        case 84:
            return require('../../assets/img/acertijos/adivinanzas84.jpg');
        case 85:
            return require('../../assets/img/acertijos/adivinanzas85.jpg');
        case 86:
            return require('../../assets/img/acertijos/adivinanzas86.jpg');
        case 87:
            return require('../../assets/img/acertijos/adivinanzas87.jpg');
        case 88:
            return require('../../assets/img/acertijos/adivinanzas88.jpg');
        case 89:
            return require('../../assets/img/acertijos/adivinanzas89.jpg');
        case 90:
            return require('../../assets/img/acertijos/adivinanzas90.jpg');
        case 91:
            return require('../../assets/img/acertijos/adivinanzas91.jpg');
        case 92:
            return require('../../assets/img/acertijos/adivinanzas92.jpg');
        case 93:
            return require('../../assets/img/acertijos/adivinanzas93.jpg');
        case 94:
            return require('../../assets/img/acertijos/adivinanzas94.jpg');
        case 95:
            return require('../../assets/img/acertijos/adivinanzas95.jpg');
        case 96:
            return require('../../assets/img/acertijos/adivinanzas96.jpg');
        case 97:
            return require('../../assets/img/acertijos/adivinanzas97.jpg');
        case 98:
            return require('../../assets/img/acertijos/adivinanzas98.jpg');
        case 99:
            return require('../../assets/img/acertijos/adivinanzas99.jpg');
        case 100:
            return require('../../assets/img/acertijos/adivinanzas100.jpg');
        case 101:
            return require('../../assets/img/acertijos/adivinanzas101.jpg');
        case 102:
            return require('../../assets/img/acertijos/adivinanzas102.jpg');
        case 103:
            return require('../../assets/img/acertijos/adivinanzas103.jpg');
        case 104:
            return require('../../assets/img/acertijos/adivinanzas104.jpg');
        case 105:
            return require('../../assets/img/acertijos/adivinanzas105.jpg');
        case 106:
            return require('../../assets/img/acertijos/adivinanzas106.jpg');
        case 107:
            return require('../../assets/img/acertijos/adivinanzas107.jpg');
        case 108:
            return require('../../assets/img/acertijos/adivinanzas108.jpg');
        case 109:
            return require('../../assets/img/acertijos/adivinanzas109.jpg');
        case 110:
            return require('../../assets/img/acertijos/adivinanzas110.jpg');
        case 111:
            return require('../../assets/img/acertijos/adivinanzas111.jpg');
        case 112:
            return require('../../assets/img/acertijos/adivinanzas112.jpg');
        case 113:
            return require('../../assets/img/acertijos/adivinanzas113.jpg');
        case 114:
            return require('../../assets/img/acertijos/adivinanzas114.jpg');
        case 115:
            return require('../../assets/img/acertijos/adivinanzas115.jpg');
        case 116:
            return require('../../assets/img/acertijos/adivinanzas116.jpg');
        case 117:
            return require('../../assets/img/acertijos/adivinanzas117.jpg');
        case 118:
            return require('../../assets/img/acertijos/adivinanzas118.jpg');
        case 119:
            return require('../../assets/img/acertijos/adivinanzas119.jpg');
        case 120:
            return require('../../assets/img/acertijos/adivinanzas120.jpg');
        case 121:
            return require('../../assets/img/acertijos/adivinanzas121.jpg');
        case 122:
            return require('../../assets/img/acertijos/adivinanzas122.jpg');
        case 123:
            return require('../../assets/img/acertijos/adivinanzas123.jpg');
        case 124:
            return require('../../assets/img/acertijos/adivinanzas124.jpg');
        case 125:
            return require('../../assets/img/acertijos/adivinanzas125.jpg');
        case 126:
            return require('../../assets/img/acertijos/adivinanzas126.jpg');
        case 127:
            return require('../../assets/img/acertijos/adivinanzas127.jpg');
        case 128:
            return require('../../assets/img/acertijos/adivinanzas128.jpg');
        case 129:
            return require('../../assets/img/acertijos/adivinanzas129.jpg');
        case 130:
            return require('../../assets/img/acertijos/adivinanzas130.jpg');
        case 131:
            return require('../../assets/img/acertijos/adivinanzas131.jpg');
        case 132:
            return require('../../assets/img/acertijos/adivinanzas132.jpg');
        case 133:
            return require('../../assets/img/acertijos/adivinanzas133.jpg');
        case 134:
            return require('../../assets/img/acertijos/adivinanzas134.jpg');
        case 135:
            return require('../../assets/img/acertijos/adivinanzas135.jpg');
        case 136:
            return require('../../assets/img/acertijos/adivinanzas136.jpg');
        case 137:
            return require('../../assets/img/acertijos/adivinanzas137.jpg');
        case 138:
            return require('../../assets/img/acertijos/adivinanzas138.jpg');
        case 139:
            return require('../../assets/img/acertijos/adivinanzas139.jpg');
        case 140:
            return require('../../assets/img/acertijos/adivinanzas140.jpg');
        case 141:
            return require('../../assets/img/acertijos/adivinanzas141.jpg');
        case 142:
            return require('../../assets/img/acertijos/adivinanzas142.jpg');
        case 143:
            return require('../../assets/img/acertijos/adivinanzas143.jpg');
        case 144:
            return require('../../assets/img/acertijos/adivinanzas144.jpg');
        case 145:
            return require('../../assets/img/acertijos/adivinanzas145.jpg');
        case 146:
            return require('../../assets/img/acertijos/adivinanzas146.jpg');
        case 147:
            return require('../../assets/img/acertijos/adivinanzas147.jpg');
        case 148:
            return require('../../assets/img/acertijos/adivinanzas148.jpg');
        case 149:
            return require('../../assets/img/acertijos/adivinanzas149.jpg');
        case 150:
            return require('../../assets/img/acertijos/adivinanzas150.jpg');
        case 151:
            return require('../../assets/img/acertijos/adivinanzas151.jpg');
        case 152:
            return require('../../assets/img/acertijos/adivinanzas152.jpg');
        case 153:
            return require('../../assets/img/acertijos/adivinanzas153.jpg');
        case 154:
            return require('../../assets/img/acertijos/adivinanzas154.jpg');
        case 155:
            return require('../../assets/img/acertijos/adivinanzas155.jpg');
        case 156:
            return require('../../assets/img/acertijos/adivinanzas156.jpg');
        case 157:
            return require('../../assets/img/acertijos/adivinanzas157.jpg');
        case 158:
            return require('../../assets/img/acertijos/adivinanzas158.jpg');
        case 159:
            return require('../../assets/img/acertijos/adivinanzas159.jpg');
        case 160:
            return require('../../assets/img/acertijos/adivinanzas160.jpg');
        case 161:
            return require('../../assets/img/acertijos/adivinanzas161.jpg');
        case 162:
            return require('../../assets/img/acertijos/adivinanzas162.jpg');
        case 163:
            return require('../../assets/img/acertijos/adivinanzas163.jpg');
        case 164:
            return require('../../assets/img/acertijos/adivinanzas164.jpg');
        case 165:
            return require('../../assets/img/acertijos/adivinanzas165.jpg');
        case 166:
            return require('../../assets/img/acertijos/adivinanzas166.jpg');
        case 167:
            return require('../../assets/img/acertijos/adivinanzas167.jpg');
        case 168:
            return require('../../assets/img/acertijos/adivinanzas168.jpg');
        case 169:
            return require('../../assets/img/acertijos/adivinanzas169.jpg');
        case 170:
            return require('../../assets/img/acertijos/adivinanzas170.jpg');
        case 171:
            return require('../../assets/img/acertijos/adivinanzas171.jpg');
        case 172:
            return require('../../assets/img/acertijos/adivinanzas172.jpg');
        case 173:
            return require('../../assets/img/acertijos/adivinanzas173.jpg');
        case 174:
            return require('../../assets/img/acertijos/adivinanzas174.jpg');
        case 175:
            return require('../../assets/img/acertijos/adivinanzas175.jpg');
        case 176:
            return require('../../assets/img/acertijos/adivinanzas176.jpg');
        case 177:
            return require('../../assets/img/acertijos/adivinanzas177.jpg');
        case 178:
            return require('../../assets/img/acertijos/adivinanzas178.jpg');
        case 179:
            return require('../../assets/img/acertijos/adivinanzas179.jpg');
        case 180:
            return require('../../assets/img/acertijos/adivinanzas180.jpg');
        case 181:
            return require('../../assets/img/acertijos/adivinanzas181.jpg');
        case 182:
            return require('../../assets/img/acertijos/adivinanzas182.jpg');
        case 183:
            return require('../../assets/img/acertijos/adivinanzas183.jpg');
        case 184:
            return require('../../assets/img/acertijos/adivinanzas184.jpg');
        case 185:
            return require('../../assets/img/acertijos/adivinanzas185.jpg');
        case 186:
            return require('../../assets/img/acertijos/adivinanzas186.jpg');
        case 187:
            return require('../../assets/img/acertijos/adivinanzas187.jpg');
        case 188:
            return require('../../assets/img/acertijos/adivinanzas188.jpg');
        case 189:
            return require('../../assets/img/acertijos/adivinanzas189.jpg');
        case 190:
            return require('../../assets/img/acertijos/adivinanzas190.jpg');
        case 191:
            return require('../../assets/img/acertijos/adivinanzas191.jpg');
        case 192:
            return require('../../assets/img/acertijos/adivinanzas192.jpg');
        case 193:
            return require('../../assets/img/acertijos/adivinanzas193.jpg');
        case 194:
            return require('../../assets/img/acertijos/adivinanzas194.jpg');
        case 195:
            return require('../../assets/img/acertijos/adivinanzas195.jpg');
        case 196:
            return require('../../assets/img/acertijos/adivinanzas196.jpg');
        case 197:
            return require('../../assets/img/acertijos/adivinanzas197.jpg');
        case 198:
            return require('../../assets/img/acertijos/adivinanzas198.jpg');
        case 199:
            return require('../../assets/img/acertijos/adivinanzas199.jpg');
        case 200:
            return require('../../assets/img/acertijos/adivinanzas200.jpg');
        case 201:
            return require('../../assets/img/acertijos/adivinanzas201.jpg');
        case 202:
            return require('../../assets/img/acertijos/adivinanzas202.jpg');
        case 203:
            return require('../../assets/img/acertijos/adivinanzas203.jpg');
        case 204:
            return require('../../assets/img/acertijos/adivinanzas204.jpg');
        case 205:
            return require('../../assets/img/acertijos/adivinanzas205.jpg');
        case 206:
            return require('../../assets/img/acertijos/adivinanzas206.jpg');
        case 207:
            return require('../../assets/img/acertijos/adivinanzas207.jpg');
        case 208:
            return require('../../assets/img/acertijos/adivinanzas208.jpg');
        case 209:
            return require('../../assets/img/acertijos/adivinanzas209.jpg');
        case 210:
            return require('../../assets/img/acertijos/adivinanzas210.jpg');
        case 211:
            return require('../../assets/img/acertijos/adivinanzas211.jpg');
        case 212:
            return require('../../assets/img/acertijos/adivinanzas212.jpg');
        case 213:
            return require('../../assets/img/acertijos/adivinanzas213.jpg');
        case 214:
            return require('../../assets/img/acertijos/adivinanzas214.jpg');
        case 215:
            return require('../../assets/img/acertijos/adivinanzas215.jpg');
        case 216:
            return require('../../assets/img/acertijos/adivinanzas216.jpg');
        case 217:
            return require('../../assets/img/acertijos/adivinanzas217.jpg');
        case 218:
            return require('../../assets/img/acertijos/adivinanzas218.jpg');
        case 219:
            return require('../../assets/img/acertijos/adivinanzas219.jpg');
        case 220:
            return require('../../assets/img/acertijos/adivinanzas220.jpg');
        case 221:
            return require('../../assets/img/acertijos/adivinanzas221.jpg');
        case 222:
            return require('../../assets/img/acertijos/adivinanzas222.jpg');
        case 223:
            return require('../../assets/img/acertijos/adivinanzas223.jpg');
        case 224:
            return require('../../assets/img/acertijos/adivinanzas224.jpg');
        case 225:
            return require('../../assets/img/acertijos/adivinanzas225.jpg');
        case 226:
            return require('../../assets/img/acertijos/adivinanzas226.jpg');
        case 227:
            return require('../../assets/img/acertijos/adivinanzas227.jpg');
        case 228:
            return require('../../assets/img/acertijos/adivinanzas228.jpg');
        case 229:
            return require('../../assets/img/acertijos/adivinanzas229.jpg');
        case 230:
            return require('../../assets/img/acertijos/adivinanzas230.jpg');
        case 231:
            return require('../../assets/img/acertijos/adivinanzas231.jpg');
        case 232:
            return require('../../assets/img/acertijos/adivinanzas232.jpg');
        case 233:
            return require('../../assets/img/acertijos/adivinanzas233.jpg');
        case 234:
            return require('../../assets/img/acertijos/adivinanzas234.jpg');
        case 235:
            return require('../../assets/img/acertijos/adivinanzas235.jpg');
        case 236:
            return require('../../assets/img/acertijos/adivinanzas236.jpg');
        case 237:
            return require('../../assets/img/acertijos/adivinanzas237.jpg');
        case 238:
            return require('../../assets/img/acertijos/adivinanzas238.jpg');
        case 239:
            return require('../../assets/img/acertijos/adivinanzas239.jpg');
        case 240:
            return require('../../assets/img/acertijos/adivinanzas240.jpg');
        case 241:
            return require('../../assets/img/acertijos/adivinanzas241.jpg');
        case 242:
            return require('../../assets/img/acertijos/adivinanzas242.jpg');
        case 243:
            return require('../../assets/img/acertijos/adivinanzas243.jpg');
        case 244:
            return require('../../assets/img/acertijos/adivinanzas244.jpg');
        case 245:
            return require('../../assets/img/acertijos/adivinanzas245.jpg');
        case 246:
            return require('../../assets/img/acertijos/adivinanzas246.jpg');
        case 247:
            return require('../../assets/img/acertijos/adivinanzas247.jpg');
        case 248:
            return require('../../assets/img/acertijos/adivinanzas248.jpg');
        case 249:
            return require('../../assets/img/acertijos/adivinanzas249.jpg');
        case 250:
            return require('../../assets/img/acertijos/adivinanzas250.jpg');
        case 251:
            return require('../../assets/img/acertijos/adivinanzas251.jpg');
        case 252:
            return require('../../assets/img/acertijos/adivinanzas252.jpg');
        case 253:
            return require('../../assets/img/acertijos/adivinanzas253.jpg');
        case 254:
            return require('../../assets/img/acertijos/adivinanzas254.jpg');
        case 255:
            return require('../../assets/img/acertijos/adivinanzas255.jpg');
        case 256:
            return require('../../assets/img/acertijos/adivinanzas256.jpg');
        case 257:
            return require('../../assets/img/acertijos/adivinanzas257.jpg');
        case 258:
            return require('../../assets/img/acertijos/adivinanzas258.jpg');
        case 259:
            return require('../../assets/img/acertijos/adivinanzas259.jpg');
        case 260:
            return require('../../assets/img/acertijos/adivinanzas260.jpg');
        case 261:
            return require('../../assets/img/acertijos/adivinanzas261.jpg');
        case 262:
            return require('../../assets/img/acertijos/adivinanzas262.jpg');
        case 263:
            return require('../../assets/img/acertijos/adivinanzas263.jpg');
        case 264:
            return require('../../assets/img/acertijos/adivinanzas264.jpg');
        case 265:
            return require('../../assets/img/acertijos/adivinanzas265.jpg');
        case 266:
            return require('../../assets/img/acertijos/adivinanzas266.jpg');
        case 267:
            return require('../../assets/img/acertijos/adivinanzas267.jpg');
        case 268:
            return require('../../assets/img/acertijos/adivinanzas268.jpg');
        case 269:
            return require('../../assets/img/acertijos/adivinanzas269.jpg');
        case 270:
            return require('../../assets/img/acertijos/adivinanzas270.jpg');
        case 271:
            return require('../../assets/img/acertijos/adivinanzas271.jpg');
        case 272:
            return require('../../assets/img/acertijos/adivinanzas272.jpg');
        case 273:
            return require('../../assets/img/acertijos/adivinanzas273.jpg');
        case 274:
            return require('../../assets/img/acertijos/adivinanzas274.jpg');
        case 275:
            return require('../../assets/img/acertijos/adivinanzas275.jpg');
        case 276:
            return require('../../assets/img/acertijos/adivinanzas276.jpg');
        case 277:
            return require('../../assets/img/acertijos/adivinanzas277.jpg');
        case 278:
            return require('../../assets/img/acertijos/adivinanzas278.jpg');
        case 279:
            return require('../../assets/img/acertijos/adivinanzas279.jpg');
        case 280:
            return require('../../assets/img/acertijos/adivinanzas280.jpg');
        default: 
            return require('../../assets/img/acertijos/adivinanzas280.jpg');
    }
}