export const emojis = (level) => {
    switch (level) {
        case 1:
            return require('../../assets/img/emojis/emojis1.jpg');
        case 2:
            return require('../../assets/img/emojis/emojis2.jpg');
        case 3:
            return require('../../assets/img/emojis/emojis3.jpg');
        case 4:
            return require('../../assets/img/emojis/emojis4.jpg');
        case 5:
            return require('../../assets/img/emojis/emojis5.jpg');
        case 6:
            return require('../../assets/img/emojis/emojis6.jpg');
        case 7:
            return require('../../assets/img/emojis/emojis7.jpg');
        case 8:
            return require('../../assets/img/emojis/emojis8.jpg');
        case 9:
            return require('../../assets/img/emojis/emojis9.jpg');
        case 10:
            return require('../../assets/img/emojis/emojis10.jpg');
        case 11:
            return require('../../assets/img/emojis/emojis11.jpg');
        case 12:
            return require('../../assets/img/emojis/emojis12.jpg');
        case 13:
            return require('../../assets/img/emojis/emojis13.jpg');
        case 14:
            return require('../../assets/img/emojis/emojis14.jpg');
        case 15:
            return require('../../assets/img/emojis/emojis15.jpg');
        case 16:
            return require('../../assets/img/emojis/emojis16.jpg');
        case 17:
            return require('../../assets/img/emojis/emojis17.jpg');
        case 18:
            return require('../../assets/img/emojis/emojis18.jpg');
        case 19:
            return require('../../assets/img/emojis/emojis19.jpg');
        case 20:
            return require('../../assets/img/emojis/emojis20.jpg');
        case 21:
            return require('../../assets/img/emojis/emojis21.jpg');
        case 22:
            return require('../../assets/img/emojis/emojis22.jpg');
        case 23:
            return require('../../assets/img/emojis/emojis23.jpg');
        case 24:
            return require('../../assets/img/emojis/emojis24.jpg');
        case 25:
            return require('../../assets/img/emojis/emojis25.jpg');
        case 26:
            return require('../../assets/img/emojis/emojis26.jpg');
        case 27:
            return require('../../assets/img/emojis/emojis27.jpg');
        case 28:
            return require('../../assets/img/emojis/emojis28.jpg');
        case 29:
            return require('../../assets/img/emojis/emojis29.jpg');
        case 30:
            return require('../../assets/img/emojis/emojis30.jpg');
        case 31:
            return require('../../assets/img/emojis/emojis31.jpg');
        case 32:
            return require('../../assets/img/emojis/emojis32.jpg');
        case 33:
            return require('../../assets/img/emojis/emojis33.jpg');
        case 34:
            return require('../../assets/img/emojis/emojis34.jpg');
        case 35:
            return require('../../assets/img/emojis/emojis35.jpg');
        case 36:
            return require('../../assets/img/emojis/emojis36.jpg');
        case 37:
            return require('../../assets/img/emojis/emojis37.jpg');
        case 38:
            return require('../../assets/img/emojis/emojis38.jpg');
        case 39:
            return require('../../assets/img/emojis/emojis39.jpg');
        case 40:
            return require('../../assets/img/emojis/emojis40.jpg');
        case 41:
            return require('../../assets/img/emojis/emojis41.jpg');
        case 42:
            return require('../../assets/img/emojis/emojis42.jpg');
        case 43:
            return require('../../assets/img/emojis/emojis43.jpg');
        case 44:
            return require('../../assets/img/emojis/emojis44.jpg');
        case 45:
            return require('../../assets/img/emojis/emojis45.jpg');
        case 46:
            return require('../../assets/img/emojis/emojis46.jpg');
        case 47:
            return require('../../assets/img/emojis/emojis47.jpg');
        case 48:
            return require('../../assets/img/emojis/emojis48.jpg');
        case 49:
            return require('../../assets/img/emojis/emojis49.jpg');
        case 50:
            return require('../../assets/img/emojis/emojis50.jpg');
        case 51:
            return require('../../assets/img/emojis/emojis51.jpg');
        case 52:
            return require('../../assets/img/emojis/emojis52.jpg');
        case 53:
            return require('../../assets/img/emojis/emojis53.jpg');
        case 54:
            return require('../../assets/img/emojis/emojis54.jpg');
        case 55:
            return require('../../assets/img/emojis/emojis55.jpg');
        case 56:
            return require('../../assets/img/emojis/emojis56.jpg');
        case 57:
            return require('../../assets/img/emojis/emojis57.jpg');
        case 58:
            return require('../../assets/img/emojis/emojis58.jpg');
        case 59:
            return require('../../assets/img/emojis/emojis59.jpg');
        case 60:
            return require('../../assets/img/emojis/emojis60.jpg');
        case 61:
            return require('../../assets/img/emojis/emojis61.jpg');
        case 62:
            return require('../../assets/img/emojis/emojis62.jpg');
        case 63:
            return require('../../assets/img/emojis/emojis63.jpg');
        case 64:
            return require('../../assets/img/emojis/emojis64.jpg');
        case 65:
            return require('../../assets/img/emojis/emojis65.jpg');
        case 66:
            return require('../../assets/img/emojis/emojis66.jpg');
        case 67:
            return require('../../assets/img/emojis/emojis67.jpg');
        case 68:
            return require('../../assets/img/emojis/emojis68.jpg');
        case 69:
            return require('../../assets/img/emojis/emojis69.jpg');
        case 70:
            return require('../../assets/img/emojis/emojis70.jpg');
        case 71:
            return require('../../assets/img/emojis/emojis71.jpg');
        case 72:
            return require('../../assets/img/emojis/emojis72.jpg');
        case 73:
            return require('../../assets/img/emojis/emojis73.jpg');
        case 74:
            return require('../../assets/img/emojis/emojis74.jpg');
        case 75:
            return require('../../assets/img/emojis/emojis75.jpg');
        case 76:
            return require('../../assets/img/emojis/emojis76.jpg');
        case 77:
            return require('../../assets/img/emojis/emojis77.jpg');
        case 78:
            return require('../../assets/img/emojis/emojis78.jpg');
        case 79:
            return require('../../assets/img/emojis/emojis79.jpg');
        case 80:
            return require('../../assets/img/emojis/emojis80.jpg');
        case 81:
            return require('../../assets/img/emojis/emojis81.jpg');
        case 82:
            return require('../../assets/img/emojis/emojis82.jpg');
        case 83:
            return require('../../assets/img/emojis/emojis83.jpg');
        case 84:
            return require('../../assets/img/emojis/emojis84.jpg');
        case 85:
            return require('../../assets/img/emojis/emojis85.jpg');
        case 86:
            return require('../../assets/img/emojis/emojis86.jpg');
        case 87:
            return require('../../assets/img/emojis/emojis87.jpg');
        case 88:
            return require('../../assets/img/emojis/emojis88.jpg');
        case 89:
            return require('../../assets/img/emojis/emojis89.jpg');
        case 90:
            return require('../../assets/img/emojis/emojis90.jpg');
        case 91:
            return require('../../assets/img/emojis/emojis91.jpg');
        case 92:
            return require('../../assets/img/emojis/emojis92.jpg');
        case 93:
            return require('../../assets/img/emojis/emojis93.jpg');
        case 94:
            return require('../../assets/img/emojis/emojis94.jpg');
        case 95:
            return require('../../assets/img/emojis/emojis95.jpg');
        case 96:
            return require('../../assets/img/emojis/emojis96.jpg');
        case 97:
            return require('../../assets/img/emojis/emojis97.jpg');
        case 98:
            return require('../../assets/img/emojis/emojis98.jpg');
        case 99:
            return require('../../assets/img/emojis/emojis99.jpg');
        case 100:
            return require('../../assets/img/emojis/emojis100.jpg');
        case 101:
            return require('../../assets/img/emojis/emojis101.jpg');
        case 102:
            return require('../../assets/img/emojis/emojis102.jpg');
        case 103:
            return require('../../assets/img/emojis/emojis103.jpg');
        case 104:
            return require('../../assets/img/emojis/emojis104.jpg');
        case 105:
            return require('../../assets/img/emojis/emojis105.jpg');
        case 106:
            return require('../../assets/img/emojis/emojis106.jpg');
        case 107:
            return require('../../assets/img/emojis/emojis107.jpg');
        case 108:
            return require('../../assets/img/emojis/emojis108.jpg');
        case 109:
            return require('../../assets/img/emojis/emojis109.jpg');
        case 110:
            return require('../../assets/img/emojis/emojis110.jpg');
        case 111:
            return require('../../assets/img/emojis/emojis111.jpg');
        case 112:
            return require('../../assets/img/emojis/emojis112.jpg');
        case 113:
            return require('../../assets/img/emojis/emojis113.jpg');
        case 114:
            return require('../../assets/img/emojis/emojis114.jpg');
        case 115:
            return require('../../assets/img/emojis/emojis115.jpg');
        case 116:
            return require('../../assets/img/emojis/emojis116.jpg');
        case 117:
            return require('../../assets/img/emojis/emojis117.jpg');
        case 118:
            return require('../../assets/img/emojis/emojis118.jpg');
        case 119:
            return require('../../assets/img/emojis/emojis119.jpg');
        case 120:
            return require('../../assets/img/emojis/emojis120.jpg');
        case 121:
            return require('../../assets/img/emojis/emojis121.jpg');
        case 122:
            return require('../../assets/img/emojis/emojis122.jpg');
        case 123:
            return require('../../assets/img/emojis/emojis123.jpg');
        case 124:
            return require('../../assets/img/emojis/emojis124.jpg');
        case 125:
            return require('../../assets/img/emojis/emojis125.jpg');
        case 126:
            return require('../../assets/img/emojis/emojis126.jpg');
        case 127:
            return require('../../assets/img/emojis/emojis127.jpg');
        case 128:
            return require('../../assets/img/emojis/emojis128.jpg');
        case 129:
            return require('../../assets/img/emojis/emojis129.jpg');
        default: 
            return require('../../assets/img/emojis/emojis129.jpg');
    }
}