export const escudos = (level) => {
    switch (level) {
        case 1:
            return require('../../assets/img/escudos/escudos1.jpg');
        case 2:
            return require('../../assets/img/escudos/escudos2.jpg');
        case 3:
            return require('../../assets/img/escudos/escudos3.jpg');
        case 4:
            return require('../../assets/img/escudos/escudos4.jpg');
        case 5:
            return require('../../assets/img/escudos/escudos5.jpg');
        case 6:
            return require('../../assets/img/escudos/escudos6.jpg');
        case 7:
            return require('../../assets/img/escudos/escudos7.jpg');
        case 8:
            return require('../../assets/img/escudos/escudos8.jpg');
        case 9:
            return require('../../assets/img/escudos/escudos9.jpg');
        case 10:
            return require('../../assets/img/escudos/escudos10.jpg');
        case 11:
            return require('../../assets/img/escudos/escudos11.jpg');
        case 12:
            return require('../../assets/img/escudos/escudos12.jpg');
        case 13:
            return require('../../assets/img/escudos/escudos13.jpg');
        case 14:
            return require('../../assets/img/escudos/escudos14.jpg');
        case 15:
            return require('../../assets/img/escudos/escudos15.jpg');
        case 16:
            return require('../../assets/img/escudos/escudos16.jpg');
        case 17:
            return require('../../assets/img/escudos/escudos17.jpg');
        case 18:
            return require('../../assets/img/escudos/escudos18.jpg');
        case 19:
            return require('../../assets/img/escudos/escudos19.jpg');
        case 20:
            return require('../../assets/img/escudos/escudos20.jpg');
        case 21:
            return require('../../assets/img/escudos/escudos21.jpg');
        case 22:
            return require('../../assets/img/escudos/escudos22.jpg');
        case 23:
            return require('../../assets/img/escudos/escudos23.jpg');
        case 24:
            return require('../../assets/img/escudos/escudos24.jpg');
        case 25:
            return require('../../assets/img/escudos/escudos25.jpg');
        case 26:
            return require('../../assets/img/escudos/escudos26.jpg');
        case 27:
            return require('../../assets/img/escudos/escudos27.jpg');
        case 28:
            return require('../../assets/img/escudos/escudos28.jpg');
        case 29:
            return require('../../assets/img/escudos/escudos29.jpg');
        case 30:
            return require('../../assets/img/escudos/escudos30.jpg');
        case 31:
            return require('../../assets/img/escudos/escudos31.jpg');
        case 32:
            return require('../../assets/img/escudos/escudos32.jpg');
        case 33:
            return require('../../assets/img/escudos/escudos33.jpg');
        case 34:
            return require('../../assets/img/escudos/escudos34.jpg');
        case 35:
            return require('../../assets/img/escudos/escudos35.jpg');
        case 36:
            return require('../../assets/img/escudos/escudos36.jpg');
        case 37:
            return require('../../assets/img/escudos/escudos37.jpg');
        case 38:
            return require('../../assets/img/escudos/escudos38.jpg');
        case 39:
            return require('../../assets/img/escudos/escudos39.jpg');
        case 40:
            return require('../../assets/img/escudos/escudos40.jpg');
        case 41:
            return require('../../assets/img/escudos/escudos41.jpg');
        case 42:
            return require('../../assets/img/escudos/escudos42.jpg');
        case 43:
            return require('../../assets/img/escudos/escudos43.jpg');
        case 44:
            return require('../../assets/img/escudos/escudos44.jpg');
        case 45:
            return require('../../assets/img/escudos/escudos45.jpg');
        case 46:
            return require('../../assets/img/escudos/escudos46.jpg');
        case 47:
            return require('../../assets/img/escudos/escudos47.jpg');
        case 48:
            return require('../../assets/img/escudos/escudos48.jpg');
        case 49:
            return require('../../assets/img/escudos/escudos49.jpg');
        case 50:
            return require('../../assets/img/escudos/escudos50.jpg');
        case 51:
            return require('../../assets/img/escudos/escudos51.jpg');
        case 52:
            return require('../../assets/img/escudos/escudos52.jpg');
        case 53:
            return require('../../assets/img/escudos/escudos53.jpg');
        case 54:
            return require('../../assets/img/escudos/escudos54.jpg');
        case 55:
            return require('../../assets/img/escudos/escudos55.jpg');
        case 56:
            return require('../../assets/img/escudos/escudos56.jpg');
        case 57:
            return require('../../assets/img/escudos/escudos57.jpg');
        case 58:
            return require('../../assets/img/escudos/escudos58.jpg');
        case 59:
            return require('../../assets/img/escudos/escudos59.jpg');
        case 60:
            return require('../../assets/img/escudos/escudos60.jpg');
        case 61:
            return require('../../assets/img/escudos/escudos61.jpg');
        case 62:
            return require('../../assets/img/escudos/escudos62.jpg');
        case 63:
            return require('../../assets/img/escudos/escudos63.jpg');
        case 64:
            return require('../../assets/img/escudos/escudos64.jpg');
        case 65:
            return require('../../assets/img/escudos/escudos65.jpg');
        case 66:
            return require('../../assets/img/escudos/escudos66.jpg');
        case 67:
            return require('../../assets/img/escudos/escudos67.jpg');
        case 68:
            return require('../../assets/img/escudos/escudos68.jpg');
        case 69:
            return require('../../assets/img/escudos/escudos69.jpg');
        case 70:
            return require('../../assets/img/escudos/escudos70.jpg');
        case 71:
            return require('../../assets/img/escudos/escudos71.jpg');
        case 72:
            return require('../../assets/img/escudos/escudos72.jpg');
        case 73:
            return require('../../assets/img/escudos/escudos73.jpg');
        case 74:
            return require('../../assets/img/escudos/escudos74.jpg');
        case 75:
            return require('../../assets/img/escudos/escudos75.jpg');
        case 76:
            return require('../../assets/img/escudos/escudos76.jpg');
        case 77:
            return require('../../assets/img/escudos/escudos77.jpg');
        case 78:
            return require('../../assets/img/escudos/escudos78.jpg');
        case 79:
            return require('../../assets/img/escudos/escudos79.jpg');
        case 80:
            return require('../../assets/img/escudos/escudos80.jpg');
        case 81:
            return require('../../assets/img/escudos/escudos81.jpg');
        case 82:
            return require('../../assets/img/escudos/escudos82.jpg');
        case 83:
            return require('../../assets/img/escudos/escudos83.jpg');
        case 84:
            return require('../../assets/img/escudos/escudos84.jpg');
        case 85:
            return require('../../assets/img/escudos/escudos85.jpg');
        case 86:
            return require('../../assets/img/escudos/escudos86.jpg');
        case 87:
            return require('../../assets/img/escudos/escudos87.jpg');
        case 88:
            return require('../../assets/img/escudos/escudos88.jpg');
        case 89:
            return require('../../assets/img/escudos/escudos89.jpg');
        case 90:
            return require('../../assets/img/escudos/escudos90.jpg');
        case 91:
            return require('../../assets/img/escudos/escudos91.jpg');
        case 92:
            return require('../../assets/img/escudos/escudos92.jpg');
        case 93:
            return require('../../assets/img/escudos/escudos93.jpg');
        case 94:
            return require('../../assets/img/escudos/escudos94.jpg');
        case 95:
            return require('../../assets/img/escudos/escudos95.jpg');
        case 96:
            return require('../../assets/img/escudos/escudos96.jpg');
        case 97:
            return require('../../assets/img/escudos/escudos97.jpg');
        case 98:
            return require('../../assets/img/escudos/escudos98.jpg');
        case 99:
            return require('../../assets/img/escudos/escudos99.jpg');
        case 100:
            return require('../../assets/img/escudos/escudos100.jpg');
        default: 
            return require('../../assets/img/escudos/escudos100.jpg');
    }
}