export const famosos = (level) => {
    switch (level) {
        case 1:
            return require('../../assets/img/comosellama/comosellama1.jpg');
        case 2:
            return require('../../assets/img/comosellama/comosellama2.jpg');
        case 3:
            return require('../../assets/img/comosellama/comosellama3.jpg');
        case 4:
            return require('../../assets/img/comosellama/comosellama4.jpg');
        case 5:
            return require('../../assets/img/comosellama/comosellama5.jpg');
        case 6:
            return require('../../assets/img/comosellama/comosellama6.jpg');
        case 7:
            return require('../../assets/img/comosellama/comosellama7.jpg');
        case 8:
            return require('../../assets/img/comosellama/comosellama8.jpg');
        case 9:
            return require('../../assets/img/comosellama/comosellama9.jpg');
        case 10:
            return require('../../assets/img/comosellama/comosellama10.jpg');
        case 11:
            return require('../../assets/img/comosellama/comosellama11.jpg');
        case 12:
            return require('../../assets/img/comosellama/comosellama12.jpg');
        case 13:
            return require('../../assets/img/comosellama/comosellama13.jpg');
        case 14:
            return require('../../assets/img/comosellama/comosellama14.jpg');
        case 15:
            return require('../../assets/img/comosellama/comosellama15.jpg');
        case 16:
            return require('../../assets/img/comosellama/comosellama16.jpg');
        case 17:
            return require('../../assets/img/comosellama/comosellama17.jpg');
        case 18:
            return require('../../assets/img/comosellama/comosellama18.jpg');
        case 19:
            return require('../../assets/img/comosellama/comosellama19.jpg');
        case 20:
            return require('../../assets/img/comosellama/comosellama20.jpg');
        case 21:
            return require('../../assets/img/comosellama/comosellama21.jpg');
        case 22:
            return require('../../assets/img/comosellama/comosellama22.jpg');
        case 23:
            return require('../../assets/img/comosellama/comosellama23.jpg');
        case 24:
            return require('../../assets/img/comosellama/comosellama24.jpg');
        case 25:
            return require('../../assets/img/comosellama/comosellama25.jpg');
        case 26:
            return require('../../assets/img/comosellama/comosellama26.jpg');
        case 27:
            return require('../../assets/img/comosellama/comosellama27.jpg');
        case 28:
            return require('../../assets/img/comosellama/comosellama28.jpg');
        case 29:
            return require('../../assets/img/comosellama/comosellama29.jpg');
        case 30:
            return require('../../assets/img/comosellama/comosellama30.jpg');
        case 31:
            return require('../../assets/img/comosellama/comosellama31.jpg');
        case 32:
            return require('../../assets/img/comosellama/comosellama32.jpg');
        case 33:
            return require('../../assets/img/comosellama/comosellama33.jpg');
        case 34:
            return require('../../assets/img/comosellama/comosellama34.jpg');
        case 35:
            return require('../../assets/img/comosellama/comosellama35.jpg');
        case 36:
            return require('../../assets/img/comosellama/comosellama36.jpg');
        case 37:
            return require('../../assets/img/comosellama/comosellama37.jpg');
        case 38:
            return require('../../assets/img/comosellama/comosellama38.jpg');
        case 39:
            return require('../../assets/img/comosellama/comosellama39.jpg');
        case 40:
            return require('../../assets/img/comosellama/comosellama40.jpg');
        case 41:
            return require('../../assets/img/comosellama/comosellama41.jpg');
        case 42:
            return require('../../assets/img/comosellama/comosellama42.jpg');
        case 43:
            return require('../../assets/img/comosellama/comosellama43.jpg');
        case 44:
            return require('../../assets/img/comosellama/comosellama44.jpg');
        case 45:
            return require('../../assets/img/comosellama/comosellama45.jpg');
        case 46:
            return require('../../assets/img/comosellama/comosellama46.jpg');
        case 47:
            return require('../../assets/img/comosellama/comosellama47.jpg');
        case 48:
            return require('../../assets/img/comosellama/comosellama48.jpg');
        case 49:
            return require('../../assets/img/comosellama/comosellama49.jpg');
        case 50:
            return require('../../assets/img/comosellama/comosellama50.jpg');
        case 51:
            return require('../../assets/img/comosellama/comosellama51.jpg');
        case 52:
            return require('../../assets/img/comosellama/comosellama52.jpg');
        case 53:
            return require('../../assets/img/comosellama/comosellama53.jpg');
        case 54:
            return require('../../assets/img/comosellama/comosellama54.jpg');
        case 55:
            return require('../../assets/img/comosellama/comosellama55.jpg');
        case 56:
            return require('../../assets/img/comosellama/comosellama56.jpg');
        case 57:
            return require('../../assets/img/comosellama/comosellama57.jpg');
        case 58:
            return require('../../assets/img/comosellama/comosellama58.jpg');
        case 59:
            return require('../../assets/img/comosellama/comosellama59.jpg');
        case 60:
            return require('../../assets/img/comosellama/comosellama60.jpg');
        case 61:
            return require('../../assets/img/comosellama/comosellama61.jpg');
        case 62:
            return require('../../assets/img/comosellama/comosellama62.jpg');
        case 63:
            return require('../../assets/img/comosellama/comosellama63.jpg');
        case 64:
            return require('../../assets/img/comosellama/comosellama64.jpg');
        case 65:
            return require('../../assets/img/comosellama/comosellama65.jpg');
        case 66:
            return require('../../assets/img/comosellama/comosellama66.jpg');
        case 67:
            return require('../../assets/img/comosellama/comosellama67.jpg');
        case 68:
            return require('../../assets/img/comosellama/comosellama68.jpg');
        case 69:
            return require('../../assets/img/comosellama/comosellama69.jpg');
        case 70:
            return require('../../assets/img/comosellama/comosellama70.jpg');
        case 71:
            return require('../../assets/img/comosellama/comosellama71.jpg');
        case 72:
            return require('../../assets/img/comosellama/comosellama72.jpg');
        case 73:
            return require('../../assets/img/comosellama/comosellama73.jpg');
        case 74:
            return require('../../assets/img/comosellama/comosellama74.jpg');
        case 75:
            return require('../../assets/img/comosellama/comosellama75.jpg');
        case 76:
            return require('../../assets/img/comosellama/comosellama76.jpg');
        case 77:
            return require('../../assets/img/comosellama/comosellama77.jpg');
        case 78:
            return require('../../assets/img/comosellama/comosellama78.jpg');
        case 79:
            return require('../../assets/img/comosellama/comosellama79.jpg');
        case 80:
            return require('../../assets/img/comosellama/comosellama80.jpg');
        case 81:
            return require('../../assets/img/comosellama/comosellama81.jpg');
        case 82:
            return require('../../assets/img/comosellama/comosellama82.jpg');
        case 83:
            return require('../../assets/img/comosellama/comosellama83.jpg');
        case 84:
            return require('../../assets/img/comosellama/comosellama84.jpg');
        case 85:
            return require('../../assets/img/comosellama/comosellama85.jpg');
        case 86:
            return require('../../assets/img/comosellama/comosellama86.jpg');
        case 87:
            return require('../../assets/img/comosellama/comosellama87.jpg');
        case 88:
            return require('../../assets/img/comosellama/comosellama88.jpg');
        case 89:
            return require('../../assets/img/comosellama/comosellama89.jpg');
        case 90:
            return require('../../assets/img/comosellama/comosellama90.jpg');
        case 91:
            return require('../../assets/img/comosellama/comosellama91.jpg');
        case 92:
            return require('../../assets/img/comosellama/comosellama92.jpg');
        case 93:
            return require('../../assets/img/comosellama/comosellama93.jpg');
        case 94:
            return require('../../assets/img/comosellama/comosellama94.jpg');
        case 95:
            return require('../../assets/img/comosellama/comosellama95.jpg');
        case 96:
            return require('../../assets/img/comosellama/comosellama96.jpg');
        case 97:
            return require('../../assets/img/comosellama/comosellama97.jpg');
        case 98:
            return require('../../assets/img/comosellama/comosellama98.jpg');
        case 99:
            return require('../../assets/img/comosellama/comosellama99.jpg');
        case 100:
            return require('../../assets/img/comosellama/comosellama100.jpg');
        case 101:
            return require('../../assets/img/comosellama/comosellama101.jpg');
        case 102:
            return require('../../assets/img/comosellama/comosellama102.jpg');
        case 103:
            return require('../../assets/img/comosellama/comosellama103.jpg');
        case 104:
            return require('../../assets/img/comosellama/comosellama104.jpg');
        case 105:
            return require('../../assets/img/comosellama/comosellama105.jpg');
        case 106:
            return require('../../assets/img/comosellama/comosellama106.jpg');
        case 107:
            return require('../../assets/img/comosellama/comosellama107.jpg');
        case 108:
            return require('../../assets/img/comosellama/comosellama108.jpg');
        case 109:
            return require('../../assets/img/comosellama/comosellama109.jpg');
        case 110:
            return require('../../assets/img/comosellama/comosellama110.jpg');
        case 111:
            return require('../../assets/img/comosellama/comosellama111.jpg');
        case 112:
            return require('../../assets/img/comosellama/comosellama112.jpg');
        case 113:
            return require('../../assets/img/comosellama/comosellama113.jpg');
        case 114:
            return require('../../assets/img/comosellama/comosellama114.jpg');
        case 115:
            return require('../../assets/img/comosellama/comosellama115.jpg');
        case 116:
            return require('../../assets/img/comosellama/comosellama116.jpg');
        case 117:
            return require('../../assets/img/comosellama/comosellama117.jpg');
        case 118:
            return require('../../assets/img/comosellama/comosellama118.jpg');
        case 119:
            return require('../../assets/img/comosellama/comosellama119.jpg');
        case 120:
            return require('../../assets/img/comosellama/comosellama120.jpg');
        case 121:
            return require('../../assets/img/comosellama/comosellama121.jpg');
        case 122:
            return require('../../assets/img/comosellama/comosellama122.jpg');
        case 123:
            return require('../../assets/img/comosellama/comosellama123.jpg');
        case 124:
            return require('../../assets/img/comosellama/comosellama124.jpg');
        case 125:
            return require('../../assets/img/comosellama/comosellama125.jpg');
        case 126:
            return require('../../assets/img/comosellama/comosellama126.jpg');
        case 127:
            return require('../../assets/img/comosellama/comosellama127.jpg');
        case 128:
            return require('../../assets/img/comosellama/comosellama128.jpg');
        case 129:
            return require('../../assets/img/comosellama/comosellama129.jpg');
        case 130:
            return require('../../assets/img/comosellama/comosellama130.jpg');
        case 131:
            return require('../../assets/img/comosellama/comosellama131.jpg');
        case 132:
            return require('../../assets/img/comosellama/comosellama132.jpg');
        case 133:
            return require('../../assets/img/comosellama/comosellama133.jpg');
        case 134:
            return require('../../assets/img/comosellama/comosellama134.jpg');
        case 135:
            return require('../../assets/img/comosellama/comosellama135.jpg');
        case 136:
            return require('../../assets/img/comosellama/comosellama136.jpg');
        case 137:
            return require('../../assets/img/comosellama/comosellama137.jpg');
        case 138:
            return require('../../assets/img/comosellama/comosellama138.jpg');
        default: 
            return require('../../assets/img/comosellama/comosellama138.jpg');
    }
}