export const logos = (level) => {
    switch (level) {
        case 1:
            return require('../../assets/img/logos/marcas1.jpg');
        case 2:
            return require('../../assets/img/logos/marcas2.jpg');
        case 3:
            return require('../../assets/img/logos/marcas3.jpg');
        case 4:
            return require('../../assets/img/logos/marcas4.jpg');
        case 5:
            return require('../../assets/img/logos/marcas5.jpg');
        case 6:
            return require('../../assets/img/logos/marcas6.jpg');
        case 7:
            return require('../../assets/img/logos/marcas7.jpg');
        case 8:
            return require('../../assets/img/logos/marcas8.jpg');
        case 9:
            return require('../../assets/img/logos/marcas9.jpg');
        case 10:
            return require('../../assets/img/logos/marcas10.jpg');
        case 11:
            return require('../../assets/img/logos/marcas11.jpg');
        case 12:
            return require('../../assets/img/logos/marcas12.jpg');
        case 13:
            return require('../../assets/img/logos/marcas13.jpg');
        case 14:
            return require('../../assets/img/logos/marcas14.jpg');
        case 15:
            return require('../../assets/img/logos/marcas15.jpg');
        case 16:
            return require('../../assets/img/logos/marcas16.jpg');
        case 17:
            return require('../../assets/img/logos/marcas17.jpg');
        case 18:
            return require('../../assets/img/logos/marcas18.jpg');
        case 19:
            return require('../../assets/img/logos/marcas19.jpg');
        case 20:
            return require('../../assets/img/logos/marcas20.jpg');
        case 21:
            return require('../../assets/img/logos/marcas21.jpg');
        case 22:
            return require('../../assets/img/logos/marcas22.jpg');
        case 23:
            return require('../../assets/img/logos/marcas23.jpg');
        case 24:
            return require('../../assets/img/logos/marcas24.jpg');
        case 25:
            return require('../../assets/img/logos/marcas25.jpg');
        case 26:
            return require('../../assets/img/logos/marcas26.jpg');
        case 27:
            return require('../../assets/img/logos/marcas27.jpg');
        case 28:
            return require('../../assets/img/logos/marcas28.jpg');
        case 29:
            return require('../../assets/img/logos/marcas29.jpg');
        case 30:
            return require('../../assets/img/logos/marcas30.jpg');
        case 31:
            return require('../../assets/img/logos/marcas31.jpg');
        case 32:
            return require('../../assets/img/logos/marcas32.jpg');
        case 33:
            return require('../../assets/img/logos/marcas33.jpg');
        case 34:
            return require('../../assets/img/logos/marcas34.jpg');
        case 35:
            return require('../../assets/img/logos/marcas35.jpg');
        case 36:
            return require('../../assets/img/logos/marcas36.jpg');
        case 37:
            return require('../../assets/img/logos/marcas37.jpg');
        case 38:
            return require('../../assets/img/logos/marcas38.jpg');
        case 39:
            return require('../../assets/img/logos/marcas39.jpg');
        case 40:
            return require('../../assets/img/logos/marcas40.jpg');
        case 41:
            return require('../../assets/img/logos/marcas41.jpg');
        case 42:
            return require('../../assets/img/logos/marcas42.jpg');
        case 43:
            return require('../../assets/img/logos/marcas43.jpg');
        case 44:
            return require('../../assets/img/logos/marcas44.jpg');
        case 45:
            return require('../../assets/img/logos/marcas45.jpg');
        case 46:
            return require('../../assets/img/logos/marcas46.jpg');
        case 47:
            return require('../../assets/img/logos/marcas47.jpg');
        case 48:
            return require('../../assets/img/logos/marcas48.jpg');
        case 49:
            return require('../../assets/img/logos/marcas49.jpg');
        case 50:
            return require('../../assets/img/logos/marcas50.jpg');
        case 51:
            return require('../../assets/img/logos/marcas51.jpg');
        case 52:
            return require('../../assets/img/logos/marcas52.jpg');
        case 53:
            return require('../../assets/img/logos/marcas53.jpg');
        case 54:
            return require('../../assets/img/logos/marcas54.jpg');
        case 55:
            return require('../../assets/img/logos/marcas55.jpg');
        case 56:
            return require('../../assets/img/logos/marcas56.jpg');
        case 57:
            return require('../../assets/img/logos/marcas57.jpg');
        case 58:
            return require('../../assets/img/logos/marcas58.jpg');
        case 59:
            return require('../../assets/img/logos/marcas59.jpg');
        case 60:
            return require('../../assets/img/logos/marcas60.jpg');
        case 61:
            return require('../../assets/img/logos/marcas61.jpg');
        case 62:
            return require('../../assets/img/logos/marcas62.jpg');
        case 63:
            return require('../../assets/img/logos/marcas63.jpg');
        case 64:
            return require('../../assets/img/logos/marcas64.jpg');
        case 65:
            return require('../../assets/img/logos/marcas65.jpg');
        case 66:
            return require('../../assets/img/logos/marcas66.jpg');
        case 67:
            return require('../../assets/img/logos/marcas67.jpg');
        case 68:
            return require('../../assets/img/logos/marcas68.jpg');
        case 69:
            return require('../../assets/img/logos/marcas69.jpg');
        case 70:
            return require('../../assets/img/logos/marcas70.jpg');
        case 71:
            return require('../../assets/img/logos/marcas71.jpg');
        case 72:
            return require('../../assets/img/logos/marcas72.jpg');
        case 73:
            return require('../../assets/img/logos/marcas73.jpg');
        case 74:
            return require('../../assets/img/logos/marcas74.jpg');
        case 75:
            return require('../../assets/img/logos/marcas75.jpg');
        case 76:
            return require('../../assets/img/logos/marcas76.jpg');
        case 77:
            return require('../../assets/img/logos/marcas77.jpg');
        case 78:
            return require('../../assets/img/logos/marcas78.jpg');
        case 79:
            return require('../../assets/img/logos/marcas79.jpg');
        case 80:
            return require('../../assets/img/logos/marcas80.jpg');
        case 81:
            return require('../../assets/img/logos/marcas81.jpg');
        case 82:
            return require('../../assets/img/logos/marcas82.jpg');
        case 83:
            return require('../../assets/img/logos/marcas83.jpg');
        case 84:
            return require('../../assets/img/logos/marcas84.jpg');
        case 85:
            return require('../../assets/img/logos/marcas85.jpg');
        case 86:
            return require('../../assets/img/logos/marcas86.jpg');
        case 87:
            return require('../../assets/img/logos/marcas87.jpg');
        case 88:
            return require('../../assets/img/logos/marcas88.jpg');
        case 89:
            return require('../../assets/img/logos/marcas89.jpg');
        case 90:
            return require('../../assets/img/logos/marcas90.jpg');
        case 91:
            return require('../../assets/img/logos/marcas91.jpg');
        case 92:
            return require('../../assets/img/logos/marcas92.jpg');
        case 93:
            return require('../../assets/img/logos/marcas93.jpg');
        case 94:
            return require('../../assets/img/logos/marcas94.jpg');
        case 95:
            return require('../../assets/img/logos/marcas95.jpg');
        case 96:
            return require('../../assets/img/logos/marcas96.jpg');
        case 97:
            return require('../../assets/img/logos/marcas97.jpg');
        case 98:
            return require('../../assets/img/logos/marcas98.jpg');
        case 99:
            return require('../../assets/img/logos/marcas99.jpg');
        case 100:
            return require('../../assets/img/logos/marcas100.jpg');
        default: 
            return require('../../assets/img/logos/marcas100.jpg');
    }
}