export const peliculas = (level) => {
    switch (level) {
        case 1:
            return require('../../assets/img/peliculas/peliculas1.jpg');
        case 2:
            return require('../../assets/img/peliculas/peliculas2.jpg');
        case 3:
            return require('../../assets/img/peliculas/peliculas3.jpg');
        case 4:
            return require('../../assets/img/peliculas/peliculas4.jpg');
        case 5:
            return require('../../assets/img/peliculas/peliculas5.jpg');
        case 6:
            return require('../../assets/img/peliculas/peliculas6.jpg');
        case 7:
            return require('../../assets/img/peliculas/peliculas7.jpg');
        case 8:
            return require('../../assets/img/peliculas/peliculas8.jpg');
        case 9:
            return require('../../assets/img/peliculas/peliculas9.jpg');
        case 10:
            return require('../../assets/img/peliculas/peliculas10.jpg');
        case 11:
            return require('../../assets/img/peliculas/peliculas11.jpg');
        case 12:
            return require('../../assets/img/peliculas/peliculas12.jpg');
        case 13:
            return require('../../assets/img/peliculas/peliculas13.jpg');
        case 14:
            return require('../../assets/img/peliculas/peliculas14.jpg');
        case 15:
            return require('../../assets/img/peliculas/peliculas15.jpg');
        case 16:
            return require('../../assets/img/peliculas/peliculas16.jpg');
        case 17:
            return require('../../assets/img/peliculas/peliculas17.jpg');
        case 18:
            return require('../../assets/img/peliculas/peliculas18.jpg');
        case 19:
            return require('../../assets/img/peliculas/peliculas19.jpg');
        case 20:
            return require('../../assets/img/peliculas/peliculas20.jpg');
        case 21:
            return require('../../assets/img/peliculas/peliculas21.jpg');
        case 22:
            return require('../../assets/img/peliculas/peliculas22.jpg');
        case 23:
            return require('../../assets/img/peliculas/peliculas23.jpg');
        case 24:
            return require('../../assets/img/peliculas/peliculas24.jpg');
        case 25:
            return require('../../assets/img/peliculas/peliculas25.jpg');
        case 26:
            return require('../../assets/img/peliculas/peliculas26.jpg');
        case 27:
            return require('../../assets/img/peliculas/peliculas27.jpg');
        case 28:
            return require('../../assets/img/peliculas/peliculas28.jpg');
        case 29:
            return require('../../assets/img/peliculas/peliculas29.jpg');
        case 30:
            return require('../../assets/img/peliculas/peliculas30.jpg');
        case 31:
            return require('../../assets/img/peliculas/peliculas31.jpg');
        case 32:
            return require('../../assets/img/peliculas/peliculas32.jpg');
        case 33:
            return require('../../assets/img/peliculas/peliculas33.jpg');
        case 34:
            return require('../../assets/img/peliculas/peliculas34.jpg');
        case 35:
            return require('../../assets/img/peliculas/peliculas35.jpg');
        case 36:
            return require('../../assets/img/peliculas/peliculas36.jpg');
        case 37:
            return require('../../assets/img/peliculas/peliculas37.jpg');
        case 38:
            return require('../../assets/img/peliculas/peliculas38.jpg');
        case 39:
            return require('../../assets/img/peliculas/peliculas39.jpg');
        case 40:
            return require('../../assets/img/peliculas/peliculas40.jpg');
        case 41:
            return require('../../assets/img/peliculas/peliculas41.jpg');
        case 42:
            return require('../../assets/img/peliculas/peliculas42.jpg');
        case 43:
            return require('../../assets/img/peliculas/peliculas43.jpg');
        case 44:
            return require('../../assets/img/peliculas/peliculas44.jpg');
        case 45:
            return require('../../assets/img/peliculas/peliculas45.jpg');
        case 46:
            return require('../../assets/img/peliculas/peliculas46.jpg');
        case 47:
            return require('../../assets/img/peliculas/peliculas47.jpg');
        case 48:
            return require('../../assets/img/peliculas/peliculas48.jpg');
        case 49:
            return require('../../assets/img/peliculas/peliculas49.jpg');
        case 50:
            return require('../../assets/img/peliculas/peliculas50.jpg');
        case 51:
            return require('../../assets/img/peliculas/peliculas51.jpg');
        case 52:
            return require('../../assets/img/peliculas/peliculas52.jpg');
        case 53:
            return require('../../assets/img/peliculas/peliculas53.jpg');
        case 54:
            return require('../../assets/img/peliculas/peliculas54.jpg');
        case 55:
            return require('../../assets/img/peliculas/peliculas55.jpg');
        case 56:
            return require('../../assets/img/peliculas/peliculas56.jpg');
        case 57:
            return require('../../assets/img/peliculas/peliculas57.jpg');
        case 58:
            return require('../../assets/img/peliculas/peliculas58.jpg');
        case 59:
            return require('../../assets/img/peliculas/peliculas59.jpg');
        case 60:
            return require('../../assets/img/peliculas/peliculas60.jpg');
        case 61:
            return require('../../assets/img/peliculas/peliculas61.jpg');
        case 62:
            return require('../../assets/img/peliculas/peliculas62.jpg');
        case 63:
            return require('../../assets/img/peliculas/peliculas63.jpg');
        case 64:
            return require('../../assets/img/peliculas/peliculas64.jpg');
        case 65:
            return require('../../assets/img/peliculas/peliculas65.jpg');
        case 66:
            return require('../../assets/img/peliculas/peliculas66.jpg');
        case 67:
            return require('../../assets/img/peliculas/peliculas67.jpg');
        case 68:
            return require('../../assets/img/peliculas/peliculas68.jpg');
        case 69:
            return require('../../assets/img/peliculas/peliculas69.jpg');
        case 70:
            return require('../../assets/img/peliculas/peliculas70.jpg');
        case 71:
            return require('../../assets/img/peliculas/peliculas71.jpg');
        case 72:
            return require('../../assets/img/peliculas/peliculas72.jpg');
        case 73:
            return require('../../assets/img/peliculas/peliculas73.jpg');
        case 74:
            return require('../../assets/img/peliculas/peliculas74.jpg');
        case 75:
            return require('../../assets/img/peliculas/peliculas75.jpg');
        case 76:
            return require('../../assets/img/peliculas/peliculas76.jpg');
        case 77:
            return require('../../assets/img/peliculas/peliculas77.jpg');
        case 78:
            return require('../../assets/img/peliculas/peliculas78.jpg');
        case 79:
            return require('../../assets/img/peliculas/peliculas79.jpg');
        case 80:
            return require('../../assets/img/peliculas/peliculas80.jpg');
        case 81:
            return require('../../assets/img/peliculas/peliculas81.jpg');
        case 82:
            return require('../../assets/img/peliculas/peliculas82.jpg');
        case 83:
            return require('../../assets/img/peliculas/peliculas83.jpg');
        case 84:
            return require('../../assets/img/peliculas/peliculas84.jpg');
        case 85:
            return require('../../assets/img/peliculas/peliculas85.jpg');
        case 86:
            return require('../../assets/img/peliculas/peliculas86.jpg');
        case 87:
            return require('../../assets/img/peliculas/peliculas87.jpg');
        case 88:
            return require('../../assets/img/peliculas/peliculas88.jpg');
        case 89:
            return require('../../assets/img/peliculas/peliculas89.jpg');
        case 90:
            return require('../../assets/img/peliculas/peliculas90.jpg');
        case 91:
            return require('../../assets/img/peliculas/peliculas91.jpg');
        case 92:
            return require('../../assets/img/peliculas/peliculas92.jpg');
        case 93:
            return require('../../assets/img/peliculas/peliculas93.jpg');
        case 94:
            return require('../../assets/img/peliculas/peliculas94.jpg');
        case 95:
            return require('../../assets/img/peliculas/peliculas95.jpg');
        case 96:
            return require('../../assets/img/peliculas/peliculas96.jpg');
        case 97:
            return require('../../assets/img/peliculas/peliculas97.jpg');
        case 98:
            return require('../../assets/img/peliculas/peliculas98.jpg');
        case 99:
            return require('../../assets/img/peliculas/peliculas99.jpg');
        case 100:
            return require('../../assets/img/peliculas/peliculas100.jpg');
        case 101:
            return require('../../assets/img/peliculas/peliculas101.jpg');
        case 102:
            return require('../../assets/img/peliculas/peliculas102.jpg');
        case 103:
            return require('../../assets/img/peliculas/peliculas103.jpg');
        case 104:
            return require('../../assets/img/peliculas/peliculas104.jpg');
        case 105:
            return require('../../assets/img/peliculas/peliculas105.jpg');
        case 106:
            return require('../../assets/img/peliculas/peliculas106.jpg');
        case 107:
            return require('../../assets/img/peliculas/peliculas107.jpg');
        case 108:
            return require('../../assets/img/peliculas/peliculas108.jpg');
        case 109:
            return require('../../assets/img/peliculas/peliculas109.jpg');
        case 110:
            return require('../../assets/img/peliculas/peliculas110.jpg');
        case 111:
            return require('../../assets/img/peliculas/peliculas111.jpg');
        case 112:
            return require('../../assets/img/peliculas/peliculas112.jpg');
        case 113:
            return require('../../assets/img/peliculas/peliculas113.jpg');
        case 114:
            return require('../../assets/img/peliculas/peliculas114.jpg');
        case 115:
            return require('../../assets/img/peliculas/peliculas115.jpg');
        case 116:
            return require('../../assets/img/peliculas/peliculas116.jpg');
        case 117:
            return require('../../assets/img/peliculas/peliculas117.jpg');
        case 118:
            return require('../../assets/img/peliculas/peliculas118.jpg');
        case 119:
            return require('../../assets/img/peliculas/peliculas119.jpg');
        case 120:
            return require('../../assets/img/peliculas/peliculas120.jpg');
        case 121:
            return require('../../assets/img/peliculas/peliculas121.jpg');
        case 122:
            return require('../../assets/img/peliculas/peliculas122.jpg');
        case 123:
            return require('../../assets/img/peliculas/peliculas123.jpg');
        case 124:
            return require('../../assets/img/peliculas/peliculas124.jpg');
        case 125:
            return require('../../assets/img/peliculas/peliculas125.jpg');
        case 126:
            return require('../../assets/img/peliculas/peliculas126.jpg');
        case 127:
            return require('../../assets/img/peliculas/peliculas127.jpg');
        case 128:
            return require('../../assets/img/peliculas/peliculas128.jpg');
        case 129:
            return require('../../assets/img/peliculas/peliculas129.jpg');
        case 130:
            return require('../../assets/img/peliculas/peliculas130.jpg');
        case 131:
            return require('../../assets/img/peliculas/peliculas131.jpg');
        case 132:
            return require('../../assets/img/peliculas/peliculas132.jpg');
        case 133:
            return require('../../assets/img/peliculas/peliculas133.jpg');
        case 134:
            return require('../../assets/img/peliculas/peliculas134.jpg');
        case 135:
            return require('../../assets/img/peliculas/peliculas135.jpg');
        case 136:
            return require('../../assets/img/peliculas/peliculas136.jpg');
        case 137:
            return require('../../assets/img/peliculas/peliculas137.jpg');
        case 138:
            return require('../../assets/img/peliculas/peliculas138.jpg');
        default: 
            return require('../../assets/img/peliculas/peliculas138.jpg');
    }
}