export const sombras = (level) => {
    switch (level) {
        case 1:
            return require('../../assets/img/sombras/shadows1.jpg');
        case 2:
            return require('../../assets/img/sombras/shadows2.jpg');
        case 3:
            return require('../../assets/img/sombras/shadows3.jpg');
        case 4:
            return require('../../assets/img/sombras/shadows4.jpg');
        case 5:
            return require('../../assets/img/sombras/shadows5.jpg');
        case 6:
            return require('../../assets/img/sombras/shadows6.jpg');
        case 7:
            return require('../../assets/img/sombras/shadows7.jpg');
        case 8:
            return require('../../assets/img/sombras/shadows8.jpg');
        case 9:
            return require('../../assets/img/sombras/shadows9.jpg');
        case 10:
            return require('../../assets/img/sombras/shadows10.jpg');
        case 11:
            return require('../../assets/img/sombras/shadows11.jpg');
        case 12:
            return require('../../assets/img/sombras/shadows12.jpg');
        case 13:
            return require('../../assets/img/sombras/shadows13.jpg');
        case 14:
            return require('../../assets/img/sombras/shadows14.jpg');
        case 15:
            return require('../../assets/img/sombras/shadows15.jpg');
        case 16:
            return require('../../assets/img/sombras/shadows16.jpg');
        case 17:
            return require('../../assets/img/sombras/shadows17.jpg');
        case 18:
            return require('../../assets/img/sombras/shadows18.jpg');
        case 19:
            return require('../../assets/img/sombras/shadows19.jpg');
        case 20:
            return require('../../assets/img/sombras/shadows20.jpg');
        case 21:
            return require('../../assets/img/sombras/shadows21.jpg');
        case 22:
            return require('../../assets/img/sombras/shadows22.jpg');
        case 23:
            return require('../../assets/img/sombras/shadows23.jpg');
        case 24:
            return require('../../assets/img/sombras/shadows24.jpg');
        case 25:
            return require('../../assets/img/sombras/shadows25.jpg');
        case 26:
            return require('../../assets/img/sombras/shadows26.jpg');
        case 27:
            return require('../../assets/img/sombras/shadows27.jpg');
        case 28:
            return require('../../assets/img/sombras/shadows28.jpg');
        case 29:
            return require('../../assets/img/sombras/shadows29.jpg');
        case 30:
            return require('../../assets/img/sombras/shadows30.jpg');
        case 31:
            return require('../../assets/img/sombras/shadows31.jpg');
        case 32:
            return require('../../assets/img/sombras/shadows32.jpg');
        case 33:
            return require('../../assets/img/sombras/shadows33.jpg');
        case 34:
            return require('../../assets/img/sombras/shadows34.jpg');
        case 35:
            return require('../../assets/img/sombras/shadows35.jpg');
        case 36:
            return require('../../assets/img/sombras/shadows36.jpg');
        case 37:
            return require('../../assets/img/sombras/shadows37.jpg');
        case 38:
            return require('../../assets/img/sombras/shadows38.jpg');
        case 39:
            return require('../../assets/img/sombras/shadows39.jpg');
        case 40:
            return require('../../assets/img/sombras/shadows40.jpg');
        case 41:
            return require('../../assets/img/sombras/shadows41.jpg');
        case 42:
            return require('../../assets/img/sombras/shadows42.jpg');
        case 43:
            return require('../../assets/img/sombras/shadows43.jpg');
        case 44:
            return require('../../assets/img/sombras/shadows44.jpg');
        case 45:
            return require('../../assets/img/sombras/shadows45.jpg');
        case 46:
            return require('../../assets/img/sombras/shadows46.jpg');
        case 47:
            return require('../../assets/img/sombras/shadows47.jpg');
        case 48:
            return require('../../assets/img/sombras/shadows48.jpg');
        case 49:
            return require('../../assets/img/sombras/shadows49.jpg');
        case 50:
            return require('../../assets/img/sombras/shadows50.jpg');
        case 51:
            return require('../../assets/img/sombras/shadows51.jpg');
        case 52:
            return require('../../assets/img/sombras/shadows52.jpg');
        case 53:
            return require('../../assets/img/sombras/shadows53.jpg');
        case 54:
            return require('../../assets/img/sombras/shadows54.jpg');
        case 55:
            return require('../../assets/img/sombras/shadows55.jpg');
        case 56:
            return require('../../assets/img/sombras/shadows56.jpg');
        case 57:
            return require('../../assets/img/sombras/shadows57.jpg');
        case 58:
            return require('../../assets/img/sombras/shadows58.jpg');
        case 59:
            return require('../../assets/img/sombras/shadows59.jpg');
        case 60:
            return require('../../assets/img/sombras/shadows60.jpg');
        case 61:
            return require('../../assets/img/sombras/shadows61.jpg');
        case 62:
            return require('../../assets/img/sombras/shadows62.jpg');
        case 63:
            return require('../../assets/img/sombras/shadows63.jpg');
        case 64:
            return require('../../assets/img/sombras/shadows64.jpg');
        case 65:
            return require('../../assets/img/sombras/shadows65.jpg');
        case 66:
            return require('../../assets/img/sombras/shadows66.jpg');
        case 67:
            return require('../../assets/img/sombras/shadows67.jpg');
        case 68:
            return require('../../assets/img/sombras/shadows68.jpg');
        case 69:
            return require('../../assets/img/sombras/shadows69.jpg');
        case 70:
            return require('../../assets/img/sombras/shadows70.jpg');
        case 71:
            return require('../../assets/img/sombras/shadows71.jpg');
        case 72:
            return require('../../assets/img/sombras/shadows72.jpg');
        case 73:
            return require('../../assets/img/sombras/shadows73.jpg');
        case 74:
            return require('../../assets/img/sombras/shadows74.jpg');
        case 75:
            return require('../../assets/img/sombras/shadows75.jpg');
        case 76:
            return require('../../assets/img/sombras/shadows76.jpg');
        case 77:
            return require('../../assets/img/sombras/shadows77.jpg');
        case 78:
            return require('../../assets/img/sombras/shadows78.jpg');
        case 79:
            return require('../../assets/img/sombras/shadows79.jpg');
        case 80:
            return require('../../assets/img/sombras/shadows80.jpg');
        case 81:
            return require('../../assets/img/sombras/shadows81.jpg');
        case 82:
            return require('../../assets/img/sombras/shadows82.jpg');
        case 83:
            return require('../../assets/img/sombras/shadows83.jpg');
        case 84:
            return require('../../assets/img/sombras/shadows84.jpg');
        case 85:
            return require('../../assets/img/sombras/shadows85.jpg');
        case 86:
            return require('../../assets/img/sombras/shadows86.jpg');
        case 87:
            return require('../../assets/img/sombras/shadows87.jpg');
        case 88:
            return require('../../assets/img/sombras/shadows88.jpg');
        case 89:
            return require('../../assets/img/sombras/shadows89.jpg');
        case 90:
            return require('../../assets/img/sombras/shadows90.jpg');
        case 91:
            return require('../../assets/img/sombras/shadows91.jpg');
        case 92:
            return require('../../assets/img/sombras/shadows92.jpg');
        case 93:
            return require('../../assets/img/sombras/shadows93.jpg');
        case 94:
            return require('../../assets/img/sombras/shadows94.jpg');
        case 95:
            return require('../../assets/img/sombras/shadows95.jpg');
        case 96:
            return require('../../assets/img/sombras/shadows96.jpg');
        case 97:
            return require('../../assets/img/sombras/shadows97.jpg');
        case 98:
            return require('../../assets/img/sombras/shadows98.jpg');
        case 99:
            return require('../../assets/img/sombras/shadows99.jpg');
        case 100:
            return require('../../assets/img/sombras/shadows100.jpg');
        case 101:
            return require('../../assets/img/sombras/shadows101.jpg');
        case 102:
            return require('../../assets/img/sombras/shadows102.jpg');
        case 103:
            return require('../../assets/img/sombras/shadows103.jpg');
        case 104:
            return require('../../assets/img/sombras/shadows104.jpg');
        case 105:
            return require('../../assets/img/sombras/shadows105.jpg');
        case 106:
            return require('../../assets/img/sombras/shadows106.jpg');
        case 107:
            return require('../../assets/img/sombras/shadows107.jpg');
        case 108:
            return require('../../assets/img/sombras/shadows108.jpg');
        case 109:
            return require('../../assets/img/sombras/shadows109.jpg');
        case 110:
            return require('../../assets/img/sombras/shadows110.jpg');
        case 111:
            return require('../../assets/img/sombras/shadows111.jpg');
        case 112:
            return require('../../assets/img/sombras/shadows112.jpg');
        case 113:
            return require('../../assets/img/sombras/shadows113.jpg');
        case 114:
            return require('../../assets/img/sombras/shadows114.jpg');
        case 115:
            return require('../../assets/img/sombras/shadows115.jpg');
        case 116:
            return require('../../assets/img/sombras/shadows116.jpg');
        case 117:
            return require('../../assets/img/sombras/shadows117.jpg');
        case 118:
            return require('../../assets/img/sombras/shadows118.jpg');
        case 119:
            return require('../../assets/img/sombras/shadows119.jpg');
        case 120:
            return require('../../assets/img/sombras/shadows120.jpg');
        case 121:
            return require('../../assets/img/sombras/shadows121.jpg');
        case 122:
            return require('../../assets/img/sombras/shadows122.jpg');
        case 123:
            return require('../../assets/img/sombras/shadows123.jpg');
        case 124:
            return require('../../assets/img/sombras/shadows124.jpg');
        case 125:
            return require('../../assets/img/sombras/shadows125.jpg');
        case 126:
            return require('../../assets/img/sombras/shadows126.jpg');
        case 127:
            return require('../../assets/img/sombras/shadows127.jpg');
        case 128:
            return require('../../assets/img/sombras/shadows128.jpg');
        case 129:
            return require('../../assets/img/sombras/shadows129.jpg');
        case 130:
            return require('../../assets/img/sombras/shadows130.jpg');
        case 131:
            return require('../../assets/img/sombras/shadows131.jpg');
        case 132:
            return require('../../assets/img/sombras/shadows132.jpg');
        case 133:
            return require('../../assets/img/sombras/shadows133.jpg');
        case 134:
            return require('../../assets/img/sombras/shadows134.jpg');
        case 135:
            return require('../../assets/img/sombras/shadows135.jpg');
        case 136:
            return require('../../assets/img/sombras/shadows136.jpg');
        case 137:
            return require('../../assets/img/sombras/shadows137.jpg');
        case 138:
            return require('../../assets/img/sombras/shadows138.jpg');
        case 139:
            return require('../../assets/img/sombras/shadows139.jpg');
        case 140:
            return require('../../assets/img/sombras/shadows140.jpg');
        case 141:
            return require('../../assets/img/sombras/shadows141.jpg');
        case 142:
            return require('../../assets/img/sombras/shadows142.jpg');
        case 143:
            return require('../../assets/img/sombras/shadows143.jpg');
        case 144:
            return require('../../assets/img/sombras/shadows144.jpg');
        case 145:
            return require('../../assets/img/sombras/shadows145.jpg');
        case 146:
            return require('../../assets/img/sombras/shadows146.jpg');
        case 147:
            return require('../../assets/img/sombras/shadows147.jpg');
        case 148:
            return require('../../assets/img/sombras/shadows148.jpg');
        case 149:
            return require('../../assets/img/sombras/shadows149.jpg');
        case 150:
            return require('../../assets/img/sombras/shadows150.jpg');
        case 151:
            return require('../../assets/img/sombras/shadows151.jpg');
        case 152:
            return require('../../assets/img/sombras/shadows152.jpg');
        case 153:
            return require('../../assets/img/sombras/shadows153.jpg');
        case 154:
            return require('../../assets/img/sombras/shadows154.jpg');
        case 155:
            return require('../../assets/img/sombras/shadows155.jpg');
        case 156:
            return require('../../assets/img/sombras/shadows156.jpg');
        case 157:
            return require('../../assets/img/sombras/shadows157.jpg');
        case 158:
            return require('../../assets/img/sombras/shadows158.jpg');
        case 159:
            return require('../../assets/img/sombras/shadows159.jpg');
        case 160:
            return require('../../assets/img/sombras/shadows160.jpg');
        case 161:
            return require('../../assets/img/sombras/shadows161.jpg');
        case 162:
            return require('../../assets/img/sombras/shadows162.jpg');
        case 163:
            return require('../../assets/img/sombras/shadows163.jpg');
        case 164:
            return require('../../assets/img/sombras/shadows164.jpg');
        case 165:
            return require('../../assets/img/sombras/shadows165.jpg');
        case 166:
            return require('../../assets/img/sombras/shadows166.jpg');
        case 167:
            return require('../../assets/img/sombras/shadows167.jpg');
        case 168:
            return require('../../assets/img/sombras/shadows168.jpg');
        case 169:
            return require('../../assets/img/sombras/shadows169.jpg');
        case 170:
            return require('../../assets/img/sombras/shadows170.jpg');
        case 171:
            return require('../../assets/img/sombras/shadows171.jpg');
        case 172:
            return require('../../assets/img/sombras/shadows172.jpg');
        default: 
            return require('../../assets/img/sombras/shadows172.jpg');
    }
}